test: &defaults
  adapter: postgresql
  encoding: unicode
  database: wakeup_<%= ENV['DBNAME'] || ENV['RAILS_ENV'] || 'test' %>
  pool: 25
  username: wakeup
  password: letmein
development:
  <<: *defaults
production:
  <<: *defaults
