test:
  id: 'push-id'
  token: 'push-token'
  master: 'push-master'
development:
  id: 'p51MIVdYS7Ce5sWuvIy8DA'
  token: 'cMZSSTRRRFKD1zu8bmEXIQ'
  master: 'vTVQYXekQ5CnhCbCSwyFfQ'
production:
  id: 'IuTz-tZ0S16zfAvRU1AsmQ'
  token: 'kb7ZuxM3R5q04IZknh1viQ'
  master: '3MO-zo3HRPKqJq-vwoDSrA'
